#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: 2021 Dirk Beyer <https://www.sosy-lab.org>
#
# SPDX-License-Identifier: Apache-2.0

import glob
import os
import sys
import pathlib

sys.dont_write_bytecode = True  # prevents writing .pyc files

script = pathlib.Path(__file__).resolve()
project_dir = script.parent
lib_dir = project_dir / "lib"

# NOTE: Referencing the wheel files alone is not enough.
# when a whl file contains an .so file it doesn't work.
for wheel in glob.glob(os.path.join(lib_dir, "*.whl")):
   sys.path.insert(0, wheel)

sys.path.insert(0, str(project_dir))
sys.path.append(str(lib_dir))

sys.setrecursionlimit(5000)   
