# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: treedata.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='treedata.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x0etreedata.proto\"\x89\x01\n\rAnnotatedTree\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\r\n\x05nodes\x18\x02 \x03(\x05\x12\r\n\x05\x64\x65pth\x18\x03 \x03(\x05\x12\x11\n\tfrom_node\x18\x04 \x03(\x05\x12\x12\n\nassignment\x18\x05 \x03(\x05\x12\x13\n\x0b\x61ssign_attr\x18\x06 \x03(\x05\x12\x10\n\x08position\x18\x07 \x03(\x05')
)




_ANNOTATEDTREE = _descriptor.Descriptor(
  name='AnnotatedTree',
  full_name='AnnotatedTree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='AnnotatedTree.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='AnnotatedTree.nodes', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='depth', full_name='AnnotatedTree.depth', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='from_node', full_name='AnnotatedTree.from_node', index=3,
      number=4, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assignment', full_name='AnnotatedTree.assignment', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='assign_attr', full_name='AnnotatedTree.assign_attr', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='position', full_name='AnnotatedTree.position', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=156,
)

DESCRIPTOR.message_types_by_name['AnnotatedTree'] = _ANNOTATEDTREE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AnnotatedTree = _reflection.GeneratedProtocolMessageType('AnnotatedTree', (_message.Message,), {
  'DESCRIPTOR' : _ANNOTATEDTREE,
  '__module__' : 'treedata_pb2'
  # @@protoc_insertion_point(class_scope:AnnotatedTree)
  })
_sym_db.RegisterMessage(AnnotatedTree)


# @@protoc_insertion_point(module_scope)
